spring:
  application:
    name: e-commerce-v2
  datasource:
    url: jdbc:mysql://localhost:3305/e_commerce?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qlalfqjsgh
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

